FROM rust:1.93-alpine as builder
RUN apk add --no-cache curl bash bc git build-base
RUN cargo install oha

FROM alpine:3.19
RUN apk add --no-cache bash curl bc
COPY --from=builder /usr/local/cargo/bin/oha /usr/local/bin/oha
WORKDIR /bench
COPY oha.sh .
CMD ["sleep", "infinity"]
