#!/bin/bash
# bench.sh: Orchestrates container lifecycle, memory measurement, and benchmarking from the host.
# Usage: ./bench.sh [ziex|leptos|solidjs|nextjs|all]


set -euo pipefail

ALL_FRAMEWORKS=(ziex leptos solidjs nextjs)
RESULTS_FILE="result.csv"
BENCH_CONTAINER="ziex_bench-bench-1"

if [ $# -gt 0 ]; then
  FRAMEWORKS=("$@")
else
  FRAMEWORKS=("${ALL_FRAMEWORKS[@]}")
fi


get_label() {
  case "$1" in
    ziex) echo "Ziex" ;;
    leptos) echo "Leptos" ;;
    solidjs) echo "SolidStart" ;;
    nextjs) echo "Next.js" ;;
    *) echo "$1" ;;
  esac
}

echo "framework,idle_mb,peak_mb,rps,p50_ms,p99_ms" > "$RESULTS_FILE"

# Start all framework containers
echo "Starting containers..."
docker compose up -d "${FRAMEWORKS[@]}" > /dev/null 2>&1
sleep 3

# Start bench container
docker compose up -d --build bench > /dev/null 2>&1
sleep 2

# Measure idle memory for all frameworks
declare -A IDLE_MEM
echo "Measuring idle memory..."
for fw in "${FRAMEWORKS[@]}"; do
  cid=$(docker compose ps -q "$fw")
  if [ -z "$cid" ]; then
    echo "  $fw: container not found" >&2
    continue
  fi
  idle_mem=$(docker stats --no-stream --format "{{.MemUsage}}" "$cid" | awk -F'/' '{print $1}' | grep -o '[0-9.]*' | head -1)
  IDLE_MEM[$fw]="${idle_mem:-0}"
done
echo ""
echo "Running benchmarks..."
echo ""

# Benchmark each framework and measure peak memory immediately after
declare -A PEAK_MEM
declare -A BENCH_RESULTS

for fw in "${FRAMEWORKS[@]}"; do
  # Run benchmark for this single framework (quiet mode, -t for real-time output)
  docker exec -t "$BENCH_CONTAINER" bash oha.sh --container --quiet "$fw" 2>&1 | \
    awk 'NR>=4 && NR<=8 {print; fflush()}'
  echo ""

  # Measure peak memory immediately after benchmark (while memory is still high)
  cid=$(docker compose ps -q "$fw")
  if [ -n "$cid" ]; then
    peak_mem=$(docker stats --no-stream --format "{{.MemUsage}}" "$cid" | awk -F'/' '{print $1}' | grep -o '[0-9.]*' | head -1)
    PEAK_MEM[$fw]="${peak_mem:-0}"
  else
    PEAK_MEM[$fw]="0"
  fi

  # Extract benchmark result for this framework
  docker cp "$BENCH_CONTAINER:/bench/result.csv" /tmp/bench_result_${fw}.csv 2>/dev/null
  result_line=$(tail -1 /tmp/bench_result_${fw}.csv)
  BENCH_RESULTS[$fw]="$result_line"
done

# Write combined results
for fw in "${FRAMEWORKS[@]}"; do
  # Parse: framework,rps,p50_ms,p99_ms
  IFS=',' read -r _ rps p50 p99 <<< "${BENCH_RESULTS[$fw]}"
  echo "$fw,${IDLE_MEM[$fw]:-0},${PEAK_MEM[$fw]:-0},$rps,$p50,$p99" >> "$RESULTS_FILE"
done

# Stop all services
docker compose stop "${FRAMEWORKS[@]}" > /dev/null 2>&1

# Pretty summary output from results
echo ""
printf '%-12s %9s %10s %10s %9s %9s\n' "Framework" "Req/s" "P50" "P99" "Idle" "Peak"
tail -n +2 "$RESULTS_FILE" | while IFS=',' read -r fw idle peak rps p50 p99; do
  label=$(get_label "$fw")
  printf '  %-12s %9.0f %8.2f ms %8.2f ms %6s MB %6s MB\n' \
    "$label" "$rps" "$p50" "$p99" "$idle" "$peak"
done

echo ""
echo "Results written to: $RESULTS_FILE"

# Generate bench.zon from results
ZON_FILE="../site/pages/bench.zon"
{
  echo "// Auto-generated by bench/bench.sh — do not edit"
  echo ".{"
  tail -n +2 "$RESULTS_FILE" | while IFS=',' read -r fw idle peak rps p50 p99; do
    label=$(get_label "$fw")
    cat <<EOF
    .{
        .id = "$fw",
        .label = "$label",
        .idle_memory_mb = $idle,
        .peak_memory_mb = $peak,
        .requests_per_sec = ${rps%.*},
        .p50_latency_ms = $p50,
        .p99_latency_ms = $p99,
    },
EOF
  done
  echo "}"
} > "$ZON_FILE"
echo "bench.zon written to $ZON_FILE"
