#!/bin/bash

RELEASE_VERSION=v$(grep -E '^\s*\.version\s*=' build.zig.zon | sed -E 's/.*"([^"]+)".*/\1/')

echo "Releasing version: $RELEASE_VERSION"

gh release create $RELEASE_VERSION -F RELEASE.md --prerelease